# Generated by Django 4.1.4 on 2023-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_excelrow_is_url_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_qr_generated',
            field=models.BooleanField(default=False),
        ),
    ]
