# Generated by Django 4.1.4 on 2023-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_file_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Сделано')], default=1),
        ),
    ]
