# Generated by Django 4.1.4 on 2023-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelrow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Сделано')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Сделано')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Сделано')], default=1, null=True),
        ),
    ]
