# Generated by Django 4.1.4 on 2023-01-12 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('excel', models.FileField(upload_to='excel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
