# Generated by Django 4.1.4 on 2023-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='excel',
            field=models.FileField(upload_to='documents/excel'),
        ),
    ]
