# Generated by Django 4.1.4 on 2023-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_file_is_parsed_alter_file_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelrow',
            name='is_url_generated',
            field=models.BooleanField(default=False),
        ),
    ]
