# Generated by Django 4.1.4 on 2023-01-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_url_is_qr_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener.template'),
        ),
    ]
